### ISSUE TITLE
llvm-tblgen segmentaion fault

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo#20] opened 2021-02-25 04:25 UTC
I tried updating my older kiss linux install on one of my rigs. Currently it has llvm 11.0.0 1 installed. During the build it failed and the kernel reports: 

[ 7888.231917] traps: llvm-tblgen[1466] general protection fault ip:7f00ffe945c1 sp:7ffdf44efdd8 error:0 in libc.so[7f00ffe33000+76000]

I am attaching relevant part of the log here:
https://pastebin.com/embed_js/AZTbzztT

Based on the recent git history I see that llvm has been updated, so I need someone to verify if they can reproduce the crash or not. 

Despite this rig being pretty old, it still have the latest gcc version gcc 10.2.0 1 so we should be getting the same codegen on x86_64 platform i suppose.

**Comment by git-bruh** [comment] 2021-02-25 06:55
Hmm, the `llvm` update went fine for me on musl (11.0.1 -> 11.1.0). Unfortunately I won't be able to test this for a while because I lost my musl chroot due to a silly typo :/

What `CFLAGS` and `CXXFLAGS` are you using ? Try setting them to `-Os (or -O2) -pipe -march=native`

If the above fails then you can try building with an existing `clang` instead of `gcc`

**Comment by kyx0r** [comment] 2021-02-25 13:10
Yes, that's what I did. I had -O3 -pipe -march=native -mtune=native, since I suspected a compiler bug or llvm bug I changed it to -O2 optimization and it did not crash. Still that is freaking disgusting. The bug is still there and someone has to fix it. I need to bisect what's at fault here.

**Comment by git-bruh** [comment] 2021-02-25 13:18
That's pretty weird... `O3` usually doesn't cause any problems, most of the issues are caused by LTO stuff.

**Comment by kyx0r** [comment] 2021-02-25 13:28
It could also be one of -march=native -mtune=native I compiled without them.

**Comment by dilyn-corner** [comment] 2021-02-25 15:16
I would expect an issue if you were using LTO, but not this issue. 
I've built `llvm` 11.1.0 on three different installs so far with no issues, I don't think this is a `CFLAGS` problem (my most aggressive being `-O3 -fno-math-errno -pipe -march=native -mtune=native`)

That log doesn't seem complete. At least, if it is, it's basically useless for me.

**Comment by kyx0r** [comment] 2021-02-25 16:09
Here is the full log : 
[llvmbuild.LOG](https://github.com/kiss-community/repo-main/files/6044250/llvmbuild.LOG)

**Comment by dilyn-corner** [comment] 2021-02-26 00:24
Shame the full log isn't more helpful. 

You're not modifying the `llvm` build at all, correct? Maybe seeing what is in `env` will help... Have you changed anything else in the 'guts'? Maybe some `gcc` change you've made or some such other alteration?

**Comment by kyx0r** [comment] 2021-02-26 00:30
No, it's a compiler bug it seems, when I remove the -march=native -mtune=native everything compiles fine, even with -O3

**Comment by dilyn-corner** [comment] 2021-02-26 00:32
Now that is quite strange

**Comment by kyx0r** [comment] 2021-02-26 00:45
Not really, compiler bugs happen quite often. Usually I run into 1 bug every month. Since the bug is somehow tied to my settings that are cpu dependant (march=native -mtune=native) you won't be able to reproduce them I suppose unless you have the same cpu as I do, which is Intel Pentium Silver N5000. That is pretty rare one to find.

**Comment by dilyn-corner** [comment] 2021-03-01 00:50
Closing because this seems to be strictly an `llvm` problem. gl :(

**Closed as completed by dilyn-corner** 2021-03-01 00:50 UTC
