### ISSUE TITLE
firefox: build error

### ISSUE THREAD

**Issue by jslick** [kiss-community/repo#18] opened 2021-02-23 06:04 UTC
When building firefox, I encounter
```
ERROR: Package alsa was not found in the pkg-config search path.
ERROR: Perhaps you should add the directory containing `alsa.pc'
ERROR: to the PKG_CONFIG_PATH environment variable
ERROR: Package 'alsa', required by 'virtual:world', not found
```
I installed alsa-lib and the build succeeded.  Should this be a make dependency of firefox?

```
# kiss owns /usr/lib/pkgconfig/alsa.pc
alsa-lib
```

**Comment by git-bruh** [comment] 2021-02-23 06:42
`alsa-lib` is marked as a dependency for firefox already, it happens rarely that `kiss` misses a dependency for big packages that have a lot of deps, but it detects them if you do `kiss b` again.

**Closed as completed** 2021-02-23 06:42 UTC

**Comment by jslick** [comment] 2021-02-23 14:19
oh gosh, I didn't even think to check the package.  Could this be considered a bug in kiss then?

**Comment by dilyn-corner** [comment] 2021-02-23 14:26
This is indeed a bug with `kiss`, I previously brought it up https://github.com/kisslinux/kiss/issues/194 but Dylan was unable to determine the cause afaik.
I think there's just some small bug in the way the list of packages to build is passed around in the `pkg_build()` function in `kiss`, but it's a mystery to us all. The lack of reproduceability is a big reason this remains unresolved; it's happened to me with as few as three packages and as many as 120.
